### ISSUE TITLE
Sending SIGUSR1 should immediately refresh

### ISSUE THREAD

**Issue by protosphere** [ultrabug/py3status#59] opened 2015-01-25 07:32 UTC
Currently, sending a SIGUSR1 to py3status will not update the output until the next refresh cycle. Is this intended behaviour, or should it behave like i3status (sending SIGUSR1 causes an immediate refresh)?

As I have my refresh interval set to 5 seconds, this isn't really optimal in some situations (eg. When displaying song info, I would rather it update immediately when changing songs).

**Comment by ultrabug** [comment] 2015-01-25 16:13
Hi @protosphere,

No this is not the intended behavior and it should refresh immediately, which version are you running please (py3status -v) ?

**Comment by ultrabug** [comment] 2015-01-25 16:22
Just as an insight that could explain what you're seeing : sending a SIGUSR1 is not blocking for py3status. This means that it clears all the caches of your modules and then iterates (waits) again.

So you may be in a situation where your modules also needs time to refresh themselves and then you end up having py3status already be in waiting mode (sleep) before your modules actually had the time to refresh so it catches it up after its next sleep. This has been a point I've always wanted to address better (aka making refresh "look" synchronous while the rest is always asynchronous).

Is that it you're experiencing ?

**Comment by protosphere** [comment] 2015-01-25 22:53
I'm running py3status 2.2 on Python 3.4.2. That does sound like  the behaviour I'm seeing, but I'll clarify anyway. 

I'll be using https://gist.github.com/protosphere/af13d7ed8c7e1d2b4c86 as a reference.
- I set my i3 bar's status_command to `pystatus -t 0 -n 5 -i <module_path>`
- The `time` module (from above) appears in the bar, refreshing every 5 seconds
- I send a SIGUSR1 to py3status. Instead of updating the time module immediately, it waits the remainder of the wait/sleep duration before refreshing again. Perhaps this could be fixed by using a non-blocking timer to wait rather than using `sleep()`?

It might be worth noting that my i3status refresh interval is set to 5 seconds.

**Comment by ultrabug** [comment] 2015-01-26 16:20
I understand, thanks for this detailed point. I see indeed a possible improvement in the code that I could do about this kind of issue.

I'll do my best to propose a solution soon this week and will surely require your help in testing it please.

Please bear with me.

**Comment by ultrabug** [comment] 2015-02-01 21:09
Hello @protosphere 

Thanks for your patience, I hope I finally figured out a nice way of handling a lively refresh of the bar which should cover the problem you reported on this issue.

Would you please test with the issue59 branch code and report back mate ?

Cheers

**Comment by protosphere** [comment] 2015-02-09 04:16
Hi,
First, I apologise for the delay in testing this.

The issue seems to remain in this version. Upon sending a USR1 signal to py3status, I can see the information being output at a higher rate than normal, however it isn't actually updating the information. This is exactly what was happening originally: Sending a USR1 would cause py3status to output another line, however the information in that line would not be updated.

issue59 branch output (I have marked where USR1 was sent): https://ghostbin.com/paste/5kgzs
master branch output: https://ghostbin.com/paste/aw9ve

**Comment by ultrabug** [comment] 2015-02-09 08:26
That's okay @protosphere. TBH, I was not satisfied with my current proposal on branch **issue59** and was going to update this bug when I'm done with branch **issue59_bis**.

**issue59_bis** is still work-in-progress but also if you feel like testing it, be my guest mate. Your input on this is really valuable as it helps me find the best solution for this matter and end up with something neat I hope :)

**Comment by abello** [comment] 2015-02-09 09:42
Hi, 

I'm experiencing the same issue. When sending a SIGUSR1, a new line is output but the output is still the same as the old one. The actual (refreshed) output only gets printed in the next refresh interval.

By looking at the code very briefly I thought that it could be a race, but sleeping before clearing caches didn't seem to help.

Thanks

**Comment by ultrabug** [comment] 2015-02-10 21:07
Hi again @abello and @protosphere 

I'm glad to tell you that my work on **issue59_bis** branch is over and contains what I believe should fix this issue ! :)

It would be great to have your feedback on it please, cheers mates

NB: I deleted the obsolete *issue59* branch

**Comment by ultrabug** [comment] 2015-02-12 13:03
Merged into master as of now, will soon become 2.3 unless I hear anything :)

**Comment by abello** [comment] 2015-02-16 07:55
Thanks for merging!

Just wondering, how do you handle pip releases? When would the bugfixes on 2.3 be available for download/upgrade via pip?

Thanks,
Aleksander

**Comment by ultrabug** [comment] 2015-02-16 23:38
@abello, I poke around some users I know to get feedback before I make a new release usually. As you can see this lead to a few fixes since this merge :)

I think I'll tag and pip/package 2.3 by Wednesday, I'll update here when done.

**Comment by ultrabug** [comment] 2015-02-17 16:02
py3status v2.3 has been released and fixes this issue ! :) enjoy !

**Closed by ultrabug** 2015-02-17 16:02 UTC
Labels: question
