### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Saduff** [ultrabug/py3status#1074] opened 2017-09-13 22:56 UTC
Hi,

There seems to be a memory leak. Looking at top, memory usage is steadily increasing, never dropping. Left the computer on over night once, in the morning py3status was using 3.2 GB of memory. :open_mouth: 
Reloading i3 takes it down to about 30 MB, but in a few hours it will be over 500 MB, always increasing.

Arch Linux 4.12.12-1-ARCH
status_command py3status -c ~/.config/i3/i3status.conf -b -s

Here's my i3status.conf:

```
general {
    colors = true
}

clock {
    format_time = " %A %d.%m.%Y {icon} %H:%M:%S"
    on_click 1 = "exec gsimplecal"
}

battery_level {
    format = "{icon} {percent}% {time_remaining}"
    notify_low_level = True
    threshold_degraded = 20
}

whatismyip {
    cache_timeout = 1
    negative_cache_timeout = 1
    format = "{icon} {ip}"
}

net_iplist {
    cache_timeout = 1
    iface_blacklist = ["lo", "wlan0"]
    format = "{format_iface}"
    format_iface = "{iface}: {ip4}"
    format_no_ip = "E: down"
    on_click 1 = "exec wicd-client -n"
}

wifi wlan0 {
    cache_timeout = 1
    format_down = " Down"
    format_up = " {bitrate} {signal_percent} {ssid} {ip}"
    on_click 1 = "exec wicd-client -n"
}

diskdata sda1 {
    cache_timeout = 30
    disk = "sda1"
    format = " /{free} GB {used_percent}%"
    on_click 1 = "exec thunar /"
}

sysdata mem {
    cache_timeout = 5
    format = "[\?color=mem  RAM: {mem_used_percent}%]"
}

sysdata cpu {
    cache_timeout = 1
    format = "[\?color=cpu  CPU: {cpu_usage}%]"
}

arch_updates {
    format = "{pacman}"
}

xrandr {
    cache_timeout = 0
    force_on_start = "eDP1=HDMI1"
}

scratchpad_async {
    format = "{counter} ⌫   "
}

order += "scratchpad_async"
order += "arch_updates"
order += "sysdata cpu"
order += "sysdata mem"
order += "diskdata sda1"
order += "wifi wlan0"
order += "net_iplist"
order += "whatismyip"
order += "battery_level"
order += "clock"
```

**Comment by lasers** [comment] 2017-09-13 23:23
Two things to try.
```
xrandr {
    cache_timeout = 0
    force_on_start = "eDP1=HDMI1"
}
```
Real-time updates. Every `0` seconds. Use `3600` (hourly) or something else.

```
scratchpad_async {
    format = "{counter} ⌫   "
}
```
I personally experienced i3 lagging / freezing with `scratchpad_async` and/or `window_title_async` as both modules need to communicate with `i3ipc` and/or `i3`. It likely is a bug on their side. Disable this next if you're still experiencing memory leak... as we'd like to rule out `xrandr`'s real-time updates first.

What version? `py3status --version`. I see we flagged `py3status` out of date and is still on `3.5` for stable version. Are you using `aur/py3status-git`?

**Comment by Saduff** [comment] 2017-09-13 23:38
I'm using py3status version 3.5 (python 3.6.2) from aur/py3status.

xrandr is not in the order though so it should be disabled? That's a recent change. It was enabled when py3status reached 3.2 GB. But the leak seems to be still there after disabling xrandr earlier today.

I'll try disabling the scratchpad next.

**Comment by lasers** [comment] 2017-09-14 00:32
>xrandr is not in the order though so it should be disabled? That's a recent change. 

Good catch. Nothing changed. If you're still experiencing the leak after `scratchpad`, you could try the `-git` version to catch up on `3.6` and `3.7rc1`.

For `3.7`, @tobes is working on "performance consideration and lowering the load footprint of py3status." and your bug reports/performance feedback would help him should you want to participate. :-)

You can try and lighten one more thing.
```
whatismyip {
    cache_timeout = 1
    negative_cache_timeout = 1
    format = "{icon} {ip}"
}
```
This would connects to outside `https://freegeoip.net/json/` every `1` seconds. Switching to `60` seconds may help. I think we also have this issue of... For every time we run `i3-restart`, we get another `py3status` instance.

**Comment by tobes** [comment] 2017-09-14 00:44
Thanks for reporting this, it's something that needs fixing.

As @lasers says the nearer we can get to finding this problem the better.
If you can find a minimal config that causes the issue that would be really
helpful.

From my take. The starting point is if this is something core to py3status
or a specific module.

**Comment by Saduff** [comment] 2017-09-14 17:33
This seems to be in py3status itself. However, modules speed up the leaking significantly.
I left py3status over night with just the clock module (same config as above). Here are the results:

```
Time    | Memory usage
--------------------------
start   | 24.9 MB
+ 2h    | 32.7 MB
+ 1h    | 38.8 MB
+ ~12h  | 96.2 MB
```

And while writing this comment, the memory usage has increased to 97 MB already and increasing slowly.

**Comment by tobes** [comment] 2017-09-15 09:08
From what I can see this is a problem with py3status version 3.5 the latest stable version 3.6 does not appear to suffer from the issue and I think master is also good (this is from very limited testing)

I'm not sure why arch is still on version 3.5 in the aur.  I've pinged the arch maintainer @Horgix on irc and here now in case he missed that.

**Comment by Saduff** [comment] 2017-09-15 19:09
I installed the git version (3.7rc1) yesterday and left it overnight with just the clock module again.
Seems the problem is still there. Or could it be a regression after 3.6?

```
Time    | Memory usage
--------------------------
start   | 24.8 MB
+ ~11h  | 70.7 MB
```

**Comment by tobes** [comment] 2017-09-17 09:25
I'm using this to monitor memory usage
`while true;  do top -bn1 | awk '/py3status/ {print  $6}' ; sleep 10; done`

I've done these tests using my standard config so they are not terribly scientific. Is it that I have to leave things running much longer to see the issue

3.5 we just keep increasing
```
28164
28288
28332
28356
28412
29152
29152
29164
29176
29176
29176
29216
30064
30072
```

master increase but then memory gets released
```
27528
27532
27532
27544
27544
27548
27576
27576
27576
27580
27584
27584
28288
28324
28324
28324
28324
28324
28324
28336
28336
28276
28276
28240
28240
27516
27516
27516
27516
27400
27400
```

**Comment by Saduff** [comment] 2017-09-17 15:05
I kept 3.7rc1 running for two days with just the clock module. This was the state before day 2:

```
Time        | Memory usage
--------------------------
midnight    | 111.7 MB (already ran for 1 day)
1 pm (+13h) | 164.6 MB
```

I ran the same command with my usual config for faster increase. I never see a decrease.

```
28,1m
28,1m
28,2m
29,1m
29,2m
29,3m
29,5m
29,5m
29,6m
30,5m
30,5m
30,6m
30,8m
30,9m
30,9m
31,2m
31,2m
31,3m
31,6m
31,7m
31,7m
32,0m
32,0m
32,0m
32,9m
33,0m
33,0m
33,3m
33,3m
33,3m
33,5m
33,5m
33,5m
33,9m
34,0m
34,0m
34,3m
34,3m
34,4m
34,5m
34,6m
34,6m
34,9m
34,9m
34,9m
35,4m
35,4m
35,4m
35,7m
35,7m
35,7m
36,0m
```

**Comment by tobes** [comment] 2017-09-21 09:49
ok having run py3status for a long period of time I see memory increases but not to the same level as you are reporting.  I need to look at what is the cause.  notification limiting is one area where we do cache things permanently which does use memory over time but that should be fairly minimal anyhow a review does no harm.

**Comment by Saduff** [comment] 2017-09-21 21:29
It's weird we're getting different results though, like something external is causing it. I literally left only `clock {}` in my config and it still goes to 100 MB or above over a longer period of time.

**Comment by ultrabug** [comment] 2017-09-24 18:16
Hi guys,

I'd just like to mention that the new release of i3 v4.14.1 fixes a i3bar memory leak.

>  i3bar: fix a memory leak

@Saduff I dunno which version you're running but the difference may very well be that you're affected by this bug?

Please check it out and report back, thanks!

**Comment by Saduff** [comment] 2017-09-25 23:19
My i3 version was 4.14.0. After upgrading to 4.14.1, it seems the leaking has slowed down considerably with my regular py3status config. Still not convinced the problem is gone completely though as I'm still seeing a steady increase, just much slower than before.

**Comment by lasers** [comment] 2017-09-27 02:22
Sometimes I leave the computer alone. Sometimes I run `i3-msg restart`. 200+MB with the latest i3 version. Two monitors, 4 `py3status` bars. http://sprunge.us/YQZX

**Comment by Mortazamakasaadi** [comment] 2017-09-27 14:06
I'm experiencing the same problem on  a Lenovo Y510p with i3 version 4.14.1 (2017-09-24) and py3status version 3.7rc1 (python 3.6.2) on a  OS: Arch Linux Kernel: x86_64 Linux 4.12.13-1-ARCH.
here is my i3status.conf:
```

general {
	colors = true
	interval = 10
}


order += "mpd_status"
order += "group netw"
order += "sysdata"
order += "xrandr"
order += "group disks"
order += "bluetooth"
order += "battery_level"
order += "volume_status"
order += "backlight"
order += "keyboard_layout"
order += "dpms"
order += "group today"

group today{
	cycle = 0
	format = " {output}{button}"
	button_next = 1
	fixed_width = True
	tztime local {
		format = "%Y-%m-%d %a %H:%M:%S"
	}
}

dpms{
          icon_off=""
          icon_on=""
}

keyboard_layout{
	format="  {layout}"
	cache_timeout = 0.5
	colors =  "us=#00ffff, ir=#859900"
	on_click 1 ="exec xkblayout-state set +1"
}

backlight{
	format=" {level}%"
	cache_timeout = 1
	button_down = 3
	button_up = 1
	cache_timeout = 0.5
}

volume_status{
        format="  {percentage}%"
        format_muted="  "
        cache_timeout = 0.5
        on_click 1 = "exec pavucontrol"
}

battery_level{
	cache_timeout = 30
	battery_id = "all"
	notify_low_level = True
	threshold_bad = 15
	threshold_degraded = 30
	threshold_full = 100
	format = "{icon} {percent}% {time_remaining}"
	blocks=""
	charging_character=" "
}

bluetooth{
	format=" {name}"
	format_prefix=" "
	format_no_conn="OFF"
	format_no_conn_prefix=" "
	cache_timeout = 1
	color_bad = "#00fff2"
	format = "{name} {mac}"
	on_click 1 = "exec blueman-manager"
}

group disks {
	cycle = 30
	format = "{output} {button}"
	click_mode = "button"
	fixed_width = True
	open = false
	disk "/" {
		format = "  %avail / %total"
	}
	disk "/home" {
		format = "  %avail / %total"
	}
}

xrandr{
	'VGA-1-1_pos' = "left-of eDP-1-1"
	'VGA-1-1_workspaces' = "5: Presentation"
	'HDMI-1-1_pos' = "left-of eDP-1-1"
	'HDMI-1-1_workspaces' = "5: Presentation"
}

sysdata{
	format="[\?color=cpu   {cpu_usage}% {cpu_temp}],[\?color=mem {mem_used}GB ({mem_used_percent}%)]"
	on_click 1 = "exec xfce4-terminal --hide-scrollbar --drop-down --command=htop --title='System Status'"
}

group netw{
	cycle = 0
	format = "{output} {button}"
	fixed_width=true
	open = false
	net_rate{
		format=" {interface} {down} {up}"
		format_no_connection="  "
	}
}

mpd_status{
	cache_timeout=0.5
	max_width=84
	state_pause=""
	state_play=""
	state_stop=""
	#color_pause=""
	#color_play=""
	#color_stop=""
	on_click 1 = "exec --no-startup-id playerctl -p cantata next"
	on_click 2 = "exec --no-startup-id playerctl -p cantata play-pause"
        on_click 3 = "exec --no-startup-id playerctl -p cantata previous"
}
```

and output of `while true; do top -bn1 | awk '/py3status/ {print $6}' ; sleep 10; done`
```
30.4m
33.5m
36.5m
39.4m
42.4m
45.1m
47.7m
50.1m
53.1m
55.9m
58.8m
61.7m
64.5m
67.4m
70.3m
73.2m
76.1m
79.0m
81.9m
84.7m
87.6m
90.4m
93.5m
96.3m
99.2m
102.1m
105.4m
107.7m
110.1m
112.9m
115.8m
118.5m
121.4m
124.3m
127.2m
130.1m
133.0m
135.9m
138.7m
141.6m
144.5m
147.4m
150.3m
153.2m
156.1m
158.9m
161.8m
164.7m
167.5m
170.4m
173.4m
176.3m
179.1m
182.0m
184.9m
187.7m
190.6m
193.4m
196.3m
199.2m
202.2m
205.0m
31.7m //reloaded i3wm
```
this is 2.9m per 10secs.
I checked memory usage with every single option in i3status.conf independently. even though memory usage slows down but its still slowly increasing over time.
only time I had no increase (10mins tested) was when i tried:
```
general {
	colors = true
	interval = 10
}
```
(removed everything from i3status.conf except lines above).
which only uses 23.1m and stays there...

**Comment by ultrabug** [comment] 2017-09-27 20:53
Thanks for reporting too @Mortazamakasaadi

So there's something with i3 / py3status and python 3.6 on Arch. I'll run py3status on 3.6 tomorrow and see if I can reproduce for me.

Quick question: rolling back i3 to 4.13 and/or python to 3.5 is hard for you Arch guys ? just to help clear stuff out

**Comment by lasers** [comment] 2017-09-28 03:24
Not hard and not familiar with python. Downgrading that one could give us issues somewhere. We don't have PKGBUILD for `aur/py3status 3.6-1` so most stays on `3.5` or `3.7rc` (git). @tobes made several (performance) PRs. Do we address this now or after? I logged 1GiB today too.

**Comment by Mortazamakasaadi** [comment] 2017-09-28 09:04
@ultrabug rolling back i3-wm is no problem(it almost has no dependents) but python is not possible.I have too many packages depending on python>=3.6.
tested:  rolling back only i3 to 4.13-1 does not resolve the issue.

**Comment by ultrabug** [comment] 2017-09-29 10:49
I've tried everything and I can't reproduce this.

## Setup:

- gentoo linux
- kernel 4.12.5
- python 3.6.1 (tried with 3.5 as well)
- py3status (master)
- i3 4.14 (the bugged one!)

## i3status config:

```
general {
	color_bad = "#dc322f"
	color_degraded = "#cb4b16"
	color_good = "#859900"
	color_separator = "#586e75"
	colors = true
	interval = 1
	markup = "pango"
}

order += "tztime local"
order += "clock"
order += "group tz"

group tz {
	cycle = 10
	format = "{output}"

	tztime la {
		format = "LA %H:%M"
		timezone = "America/Los_Angeles"
	}

	tztime ny {
		format = "NY %H:%M"
		timezone = "America/New_York"
	}

	tztime du {
		format = "DU %H:%M"
		timezone = "Asia/Dubai"
	}
}

tztime local {
	format = "%d/%m %H:%M:%S"
}
```

## Runtime options:

I've also tried forcing a very fast loop interval to 100ms to increase the probability rate of the memory leak... nothing. @Saduff @Mortazamakasaadi can you try this trick as well to see if it's related to the number of iterations?
```
py3status -b -c ~/.i3/i3status_leak.conf -t 1 -n 0.1
```

## Results:
Absolutely steady RAM consumption...

I'll try to dig more later... :(

**Comment by coalwater** [comment] 2017-09-29 11:06
@ultrabug I think it's related to certain modules, my set up contains 3 status bars ( 2 on main screen and 1 on external monitor ), only one of them is leaking, so maybe it's related to the modules on that status bar.

The one that's leaking contains those modules: wifi, ethernet, online_status, net_rate, group ( two diskdata ones ), sysdata, pomodoro and weather_yahoo.

I'm gonna start removing modules one by one till i see which module might be causing this.

**Comment by lasers** [comment] 2017-09-29 12:51
It does not change much when I'm not using the computer so is that an i3 or i3bar issue? Here's the updated log: http://sprunge.us/REHP

**Comment by coalwater** [comment] 2017-09-29 12:58
For me I found that `net_rate` and `online_status` contribute the most to the leak, here's a config file is enough to reproduce the issue for me
```
general {
  colors = true
  interval = 1
  separator = ' | '
}

order += "net_rate"
order += "online_status"

online_status {
  cache_timeout = 1
  format = '{icon}'
  icon_on = ''
  icon_off = ''
}

net_rate {
  cache_timeout = 1
  unit = 'kB/s'
  format = "[\?color=up {up}]   [\?color=down {down}]"
}
```

**Comment by Mortazamakasaadi** [comment] 2017-09-30 08:51
@ultrabug I tested your i3status.conf, it is steady here as well, I ran it for 20min and it used only 23.6m of memory. so this memory leakage is related to some of modules...
weird thing is when I am using my own config for tz time (a bit different from yours):
```

general {
        colors = true
        interval = 10
}


order += "group today"

group today{
        cycle = 0
        format = " {output}{button}"
        button_next = 1
        fixed_width = True
        tztime local {
                format = "%Y-%m-%d %a %H:%M:%S"
        }
}
```
this is the result:
```
23.4m                                
23.4m                                
23.4m                                
23.4m                                
23.4m                                
23.4m                                
23.4m                                
23.4m                                
23.5m                                
23.5m                                
23.5m                                
23.5m                                
23.5m                                
23.5m                                
23.5m                                
23.5m                                
23.5m                                
23.6m                                
23.6m   
23.6m                                
23.6m                                
23.6m                                
23.6m                                
23.6m                                
23.6m                                
23.6m                                
23.7m                                
23.7m                                
23.7m                                
23.7m 
.
.
.
30.5m 
``` 
it usage of memory is around 0.1m/90sec. I don't know whether it gets garbage collected.
I am running py3status with:
`py3status -c ~/.config/i3/i3status.conf -n 5`

**Comment by ultrabug** [comment] 2017-10-22 16:02
An update here, I've been running py3status for days with given modules and can't reproduce still.

We have been merging a lot of improvements lately, can you guys update master and report again?

Thanks

**Comment by stpnk** [comment] 2017-11-09 14:03
Hello! I had a huge memory leak earlier too but after update it seems like all works fine.
Linux arch 4.13.11-1-ARCH
i3-wm 4.14.1-2
py3status 3.6-1 from AUR

**Comment by Saduff** [comment] 2017-11-15 00:02
Seems the memory leak is gone for me, too. Not sure what fixed it.
24h uptime and py3status is still at a steady 29.4m.

kernel 4.13.11-1-ARCH
py3status version 3.7rc1 (python 3.6.3)
i3 version 4.14.1

Installed py3status-git from AUR on 09 Nov, but seems version is still 3.7rc1. Other differences are the kernel version and python version.

**Comment by lasers** [comment] 2017-12-03 17:31
Can we close this now?

**Comment by coalwater** [comment] 2017-12-03 19:49
For me I don't have this issue anymore, I have no reason to keep it open.

**Comment by ultrabug** [comment] 2017-12-07 13:54
Thanks everyone for your reports and following up on this issue. I'm happy this issue served as a good excuse to find nice ways to improve py3status performance!

**Closed by ultrabug** 2017-12-07 13:54 UTC
