### ISSUE TITLE
xrandr module cause screen freeze for ~0.5 second every time it refreshes

### ISSUE THREAD

**Issue by blahgeek** [ultrabug/py3status#580] opened 2016-11-21 09:42 UTC
In my laptop (XPS 15), running `xrandr` would make the screen freeze for a short period of time (~0.5 second). So, with xrandr module enabled, py3status would make the screen freeze every time it refreshes, it's especially noticeable while playing movie etc.

I am not sure whether this would happen for every one, but at least I am not alone (e.g. http://unix.stackexchange.com/questions/185529/why-does-querying-xrandr-briefly-freeze-the-screen).

It's not a bug for py3status but I think it would be great to mention it in the documentation (it takes me quite a while to locate the source of the problem). My solution is to set the `cache_timeout` of `xrandr` module to a very large number, and it would still update it's value if I click it.

**Comment by tobes** [comment] 2017-08-27 13:22
I am currently being affected by this

**Comment by cyrinux** [comment] 2018-04-10 12:49
I have the same bug too, visible for example when trying to play to openarena, freeze at every refresh

**Comment by lasers** [comment] 2018-05-02 04:51
@ultrabug Close this?

**Comment by ultrabug** [comment] 2018-05-02 07:35
Well there are users still affected, so not really :( I can't reproduce tho, it's a bit frustrating

**Comment by lasers** [comment] 2018-05-02 08:15
I experienced this before. Poor drivers, poor graphics, poor performance, poor hardwares, poor kernel, poor Xorg, poor libs, poor support, etc. Really, it could be anything. It could work without for years, then issues slowly creeps up... The solution can be to downgrade packages, downgrade kernels, or to use a different linux distribution hopefully with better supports.

Example: https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/855124

All of them are outside of scope for `xrandr` module which does nothing more than causing problems for affected users because it would query `xrandr` command every ten seconds. Running `$ while true; do xrandr && sleep 10; done` in the terminal likely could give affected users same effects.

IIRC @tobes ran into this issue when he upgraded the system to new Fedora release.

Also,
>@blahgeek It's not a bug for py3status but I think it would be great to mention it in the documentation (it takes me quite a while to locate the source of the problem). My solution is to set the cache_timeout of xrandr module to a very large number, and it would still update it's value if I click it.

Documented! Done! Next! >_>

**Comment by ultrabug** [comment] 2018-05-08 15:41
You're right, since it's documented now, let's close this. Thanks mates!

**Closed by ultrabug** 2018-05-08 15:41 UTC
Labels: bug
