### ISSUE TITLE
Time and Tztime produce Date twice

### ISSUE THREAD

**Issue by macxcool** [ultrabug/py3status#289] opened 2016-04-25 21:54 UTC
Whenever I add 'time' or 'tztime' to my config, the i3bar shows my format + another instance of 'YYYY MM DD' after it. I'm not sure if this is a problem with py3status or something I'm missing.

**Comment by tobes** [comment] 2016-04-25 22:04
hmm, what version of py3status are you using?  `py3status -v`, or are you running from master?

Could you also provide a minimal `i3status.config` that creates the issue

**Comment by macxcool** [comment] 2016-04-26 11:23
Yes;

# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        colors = true
        interval = 5
        output_format = "i3bar"
}

order += "tztime local"
#order += "time"

tztime local {
        format = "%a %b%e %H:%M"
}


RIght now I'm seeing:           Tue Apr26 07:22 2016 04 26
+ some tray items.

On Mon, Apr 25, 2016 at 6:04 PM, tobes <notifications@github.com> wrote:

> hmm, what version of py3status are you using? py3status -v, or are you
> running from master?
>
> Could you also provide a minimal i3status.config that creates the issue
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ultrabug/py3status/issues/289#issuecomment-214543267>
>



-- 
 _  _           _     ___         _
 )\/,) ___  __  )L,   ))  __  __  )) __ _ _
((`(( ((_( (|  ((\   ((__((_)((_)(( (('((\(

**Comment by macxcool** [comment] 2016-04-26 11:23
py3status 2.9
python 3.5.1
I'm running Archlinux 64-bit with everything up-to-date.

**Comment by tobes** [comment] 2016-04-26 12:15
Confirmed as an issue in version 2.9

The problem is `%e` if you use `%d` it will work although it will be zero padded.

This is actually fixed (from what I can tell, but today is the 26th) in master so in the 3.0 release due soon, this will be working as expected.

Thanks for reporting this.

**Comment by macxcool** [comment] 2016-04-26 12:26
No prob. I'll try the master branch tonight. I just hate all that wasted
space ;-)

On Tue, Apr 26, 2016 at 8:15 AM, tobes <notifications@github.com> wrote:

> Confirmed as an issue in version 2.9
>
> The problem is %e if you use %d it will work although it will be zero
> padded.
>
> This is actually fixed (from what I can tell, but today is the 26th) in
> master so in the 3.0 release due soon, this will be working as expected.
>
> Thanks for reporting this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ultrabug/py3status/issues/289#issuecomment-214720592>
>



-- 
 _  _           _     ___         _
 )\/,) ___  __  )L,   ))  __  __  )) __ _ _
((`(( ((_( (|  ((\   ((__((_)((_)(( (('((\(

**Comment by macxcool** [comment] 2016-04-26 19:25
Tested with current git extract. Problem goes away. Excellent!

**Comment by ultrabug** [comment] 2016-05-18 11:11
Good news, closing thanks !

**Closed by ultrabug** 2016-05-18 11:11 UTC
Labels: question
