### ISSUE TITLE
Time doesn't update unless using default format '%Y-%m-%d %H:%M:%S'

### ISSUE THREAD

**Issue by epaaj** [ultrabug/py3status#221] opened 2016-03-24 08:17 UTC
I updated from py3status 2.6 to 2.9 recently and noticed that the displayed time doesn't update as usual. It seems the problem started with version 2.7 as I have the same problem with this version.

I've been displaying the time formatted as 'w%V %Y-%m-%d %H:%M:%S' to include the week number as well. But this seems to make the displayed time to update only once every minute (if using the computer). When I unlocked i3lock this morning the time was stuck at 15:45, the time I locked the screen yesterday.

I believe the issue started with this commit: https://github.com/ultrabug/py3status/commit/870491ab89413d0395358c13fde99e7e95abcda8

I have not yet been able to fix the problem myself.

**Comment by tobes** [comment] 2016-03-24 10:00
I can confirm this is an issue and was working in 2.6.

Looking at an exception happens here https://github.com/ultrabug/py3status/blob/master/py3status/i3status.py#L390

It looks like it worked 'by accident' previously.

**Comment by tobes** [comment] 2016-03-24 12:05
@ultrabug my thoughts on this are to simplify things.

Give i3status a fixed format so we can detect the delta and then use the user supplied format to create the displayed time/date - doing that should then work with any valid date formats including %Z

If you're happy with this idea I can knock out some code it should be fairly easy

**Comment by ultrabug** [comment] 2016-03-24 14:23
Well I love your enthusiasm @tobes since my experience with handling date formats from the C based i3status and python has always resulted in complex stuff (which inevitably lead to this issue)...

So by all means, if you can tackle something fairly easily, be my most welcomed guest ! :)

Thanks

**Comment by pydsigner** [comment] 2016-03-24 15:05
Why are we even doing this through i3status? We should just have a module for this.

**Comment by tobes** [comment] 2016-03-24 15:43
> Why are we even doing this through i3status? We should just have a module for this.

It's nice too keep compatibility for people switching from i3status.

But yeah a module works too.  I've made a lovely one but I'm wanting before offering it up, as I want to allow lists in the config first and that will take time to do nicely (multi-line lists)

**Comment by tobes** [comment] 2016-03-25 00:31
Hmm, 

Never work with children, animals or datetimes...

I've had a play and this is my current patch.  It is based on my 'speedy' branch as that moved the i3status time code around. I'm hoping that will be merged at some point, if not this can easily be adapted.

It's not perfect but now deals with 'odd' formatting like %V (week no) %Z (timezone).  Things like %A (day name) are non-localized but correct eg `Europe\Berlin` shows `Saturday` not `Samstag` with my locale (I'm not sure how i3status deblt with this)

patch
https://github.com/tobes/py3status/commit/e11ac996f529095c1b17925bfe87682c5989020f

full branch
https://github.com/tobes/py3status/tree/time-fix-speedy

I can make this a formal pull request

This is my favourite patch as it reduces the number of lines of code :)

**Closed** 2016-03-29 07:08 UTC
Labels: bug
