### ISSUE TITLE
Instance 'wifi', user method 'get_wifi' failed...

### ISSUE THREAD

**Issue by RomanSC** [ultrabug/py3status#572] opened 2016-11-17 15:31 UTC
On startup and restart in i3wm, I get the following error:
`py3status: Instance 'wifi', user method 'get_wifi' failed (CalledProcessError) wifi.py line 97. Please try to fix this and reload i3wm`

Operating System, up to date:
Arch Linux
4.8.7-1-ARCH

Py3status/Python version:
py3status version 3.2 (python 3.5.2)

i3wm version:
i3 version 4.13 (2016-11-08)

Py3status config:

```
# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

#order += "window_title"
#order += "spotify"
order += "volume_status"
order += "wifi"
order += "ethernet enp3s0"
#order += "run_watch VPN"
order += "battery_level"
#order += "arch_updates"
order += "time"

general {
	color_good = "#FFFFFF"
	color_degraded = "#FFFFFF"
	color_bad = "#FFFFFF"
	interval = 1
	output_format = "i3bar"
}

volume_status {
	format = " {percentage}%"
	format_muted = " {percentage}%"
	device = "default"
	on_click 1 = "exec pavucontrol"
	on_click 2 = "exec ponymix toggle"
	on_click 3 = "exec pulseaudio-equalizer-gtk"
	on_click 4 = "exec ponymix increase 5"
	on_click 5 = "exec ponymix decrease 5"
}

spotify {
	format = "{title} - {artist}"
	format_down = "down"
	format_stopped = "{title} - {artist}"
}

wifi {
	bitrate_bad = 26
	bitrate_degraded = 53
	cache_timeout = 1
	device = 'wlp3s0'
	format_down = 'down'
	format_up = '  {signal_percent} {ssid}'
	round_bitrate = true
	signal_bad = 29
	signal_degraded = 49
	use_sudo = true
}

ethernet enp3s0 {
	format_up = " %ip"
	format_down = "down"
}

run_watch VPN {
	format = "up"
	format_down = "down"
	pidfile = "/var/run/vpnc/pid"
}

battery_level {
	#battery_id = 'all'
	#cache_timeout = 1
	#charging_character = " "
	format = "B: {percent}%"
	#
}

time {
	format = "%a, %b %d %I:%M"
}

```

Glad to provide any other helpful info I can. Will update if I solve the issue.

**Comment by RomanSC** [comment] 2016-11-17 15:50
Running iw dev produces the following (Underline, is my edit as not to reveal IP):

phy#0
	Interface wlp3s0
		ifindex 2
		wdev 0x1
		addr _______________
		ssid ________ _______
		type managed
		channel 1 (2412 MHz), width: 20 MHz, center1: 2412 MHz
		txpower 15.00 dBm

**Comment by tobes** [comment] 2016-11-17 16:09
This was caused by `use_sudo = true` so we need better feedback to the user.

**Comment by RomanSC** [comment] 2016-11-17 17:36
Thanks for the help tobes!

**Comment by lasers** [comment] 2017-02-08 23:59
Closed via https://github.com/ultrabug/py3status/issues/572

**Comment by tobes** [comment] 2017-02-09 15:19
#725 actually causes this issue to re-occur.

anyhow we should have a fix in the next few days from @lasers

**Closed** 2017-02-14 11:48 UTC
