### ISSUE TITLE
module_test needs to use full stack

### ISSUE THREAD

**Issue by lasers** [ultrabug/py3status#806] opened 2017-03-14 03:17 UTC
Good.
```
lasers~/src/py3status git:(2884c2d3) python3 ~/src/py3status/py3status/modules/dpms.py
{'cached_until': 1489461092.0, 'full_text': 'DPMS', 'color': '#00FF00'}
```
Bad.
```
lasers~/src/py3status git:(e3ed835a) python3 ~/src/py3status/py3status/modules/dpms.py
{'cached_until': 1489461086.0, 'full_text': 'DPMS', 'color': None}
```
Bisect. 
```
e3ed835ae532c3b6e039a754e1f42752461d9a7e is the first bad commit
```
commit e3ed835ae532c3b6e039a754e1f42752461d9a7e
Author: Toby Dacre
Date:   Mon Feb 20 22:24:12 2017 +0000

    fix color comparison bug

**Comment by tobes** [comment] 2017-03-14 10:25
The thing is if you run py3status then you will find that this commit does actually fix a bug.

The problem is that `module_test.py` has fallen behind in terms of replicating the stack.  The solution to this problem is going to be to run the standalone module more completely through the stack. Which either needs some reworking of the current code (will take time) improved fakery (will suffer from the same issue sometime in the future).

In the mean time we can paper over the cracks by setting `color_on` etc in `module_test.py` so I think I'll add a PR to do that.

**Comment by lasers** [comment] 2017-04-11 17:34
None of this `color comparsion` thing in terminal... I could live with that.
None of this `post-config-hook` thing in terminal... It hurts me badly.

**Comment by lasers** [comment] 2017-07-22 00:06
I think `module_test.py` is too behind to keep this issue open. There are likely some other issues too therefore we acknowledge that `module_test.py` is not always perfect and may need a rewritten to...
> run the standalone module more completely through the stack. Which either needs some reworking of the current code (will take time) or improved fakery (will suffer from the same issue sometime in the future).

We assume that everybody tests the module live on the statusbar too when they're fixing things up... and that we can see the colors working correctly. Going to close this color nitpick issue.

**Comment by tobes** [comment] 2017-07-22 10:26
I've renamed this and am reopening as it is an issue that needs fixing and it is good to have this info somewhere.  It will still take a while as it will need a series of PRs to unpick things.

**Comment by tobes** [comment] 2017-08-11 11:23
closing as since #975 we have improved the situation enough to close this

**Closed by tobes** 2017-08-11 11:23 UTC
