### ISSUE TITLE
Add option to format bluetooth module output if there's no adapter detected

### ISSUE THREAD

**Issue by jose1711** [ultrabug/py3status#1862] opened 2019-11-11 23:19 UTC
I currently see no way of configuring the icon/text when using bluetooth module. If there is something wrong with the adapter, the text just says: "bluetooth". It would be nice if a user can define that for instance a greyed out bluetooth icon is shown instead.

**Comment by lasers** [comment] 2019-11-12 06:43
Try https://github.com/ultrabug/py3status/tree/newmodule-bluetooth.

**Comment by jose1711** [comment] 2019-11-12 07:33
thank you, though this fails on my test arch linux system inside virtualbox. seems like with missing bluetooth adapter `bluetooth.service` is unable to start and the module cannot cope with such a situation

**Comment by lasers** [comment] 2019-11-12 07:45
Is there an error message from the module? Just in case you didn't see... What you want is not in default `format`. (See third example). Otherwise, I need more info.

**Comment by jose1711** [comment] 2019-11-12 08:28
![obrázok](https://user-images.githubusercontent.com/1406222/68654600-8d91d280-052e-11ea-8af0-5935012b1967.png)
![obrázok](https://user-images.githubusercontent.com/1406222/68654615-9c788500-052e-11ea-82d4-1369771d0618.png)
it looks as it is failing earlier than the formatting starts.

**Comment by lasers** [comment] 2019-11-12 08:53
I can reproduce this by uninstalling `bluez` stuff. Do you have them installed on virtualbox?

That error message is pretty nasty tho... The problem might be unrelated to the adapter too because I didn't have issues running/testing `bluetooth` module without the adapter.

**Comment by jose1711** [comment] 2019-11-12 10:44
I do have `bluez` package installed inside VirtualBox. I should have an option to test this on a real computer lacking bluetooth adapter later this week.

**Comment by lasers** [comment] 2019-11-12 10:48
No problem. I recently added a new exciting commit. My old bluetooth mouse is really flakey. :(

**Comment by jose1711** [comment] 2019-11-12 13:36
Thank you, the new commit works nicely. How long before this is pulled into main branch?

**Comment by jose1711** [comment] 2019-11-12 22:02
I'd like to add a few additional information. On Arch the bluetooth service file contains the following check:
```
ConditionPathIsDirectory=/sys/class/bluetooth
```
Without this the service is not started and `py3status` reports an issue. The directory is not created by default inside my VirtualBox machine but when I start the service manually no error is reported  by systemd, the directory gets created and `py3status` stops failing.

**Comment by lasers** [comment] 2019-11-12 22:43
>If there is something wrong with the adapter, the text just says: "bluetooth".

I now realize this is likely an error message you saw. You can click on that if you want.
Click-1 to show the error. Click-2 to refresh/retry. Click-3 to hide/dismiss the module.

**Comment by lasers** [comment] 2019-12-12 08:36
@ultrabug Bluetooth issue technically unrelated to py3status. **WDYWTD?**

1) Close this?
2) Merge `newmodule-bluetooth`?
     i) 20+ placeholders.
    ii) Includes adapters.
    iii) No more hardcoded `color`.
    iv) Code looks clean.

**Closed** 2022-10-02 13:57 UTC
Labels: feature request :pray:
