### ISSUE TITLE
keyboard_layouts Greek with polytonic variant set causes on_click error

### ISSUE THREAD

**Issue by Madcliff** [ultrabug/py3status#1987] opened 2020-12-28 17:18 UTC
After setting via setxkbmap greek to polytonic, when I define 'gr' in layouts trying to switch to the layout causes it to return a layout error. 

I am not sure if I am doing the configuration wrong?

**Comment by lasers** [comment] 2020-12-30 01:50
What's the commands to debug this? Can you try `xkb_input module` too?

**Comment by ultrabug** [comment] 2021-01-25 09:30
Closing as opener did not answer yet, if you do mate, plz reopen

**Closed by ultrabug** 2021-01-25 09:30 UTC

**Comment by lasers** [comment] 2021-01-26 10:52
Something like `setxkbmap 'gr' -variant 'polytonic'`. I hadn't used i3 in a while.

**Comment by lasers** [comment] 2021-01-30 23:39
(FYI) I can't reproduce this.
