### ISSUE TITLE
sysdata alignment should apply to the whole output of the module

### ISSUE THREAD

**Issue by ccryx** [ultrabug/py3status#815] opened 2017-03-15 13:54 UTC
When setting align = 'left' and a min_width larger than the sysdata output, the individual elements (default: CPU info, comma, memory info) get left aligned but the whole min_width is evenly divided among them.

In the attached screenshot of i3bar, min_width is set to 1360 (a bit less than my screen width).
![py3status_sysdata](https://cloud.githubusercontent.com/assets/4788195/23951670/226a6bae-098f-11e7-9a5d-b330e3513162.png)

**Comment by lasers** [comment] 2017-03-16 13:23
Confirmed. This seems like formatter and/or color issue. If you remove comma (in sysdata format), it worked correctly as long as they're same color.

I find Netdata have this issue too. It looks like the different color between two things causes the divide. With `align = left` + `min_width = 500`, I can see Netdata splitting/combining the speed + traffic values constantly if I play some videos... kinda similar to how the separator fix for frame #789 issue will only appear sometimes.

**Comment by ccryx** [comment] 2017-03-16 16:29
I think this boils down to the different elements of sysdata being output as separate JSON objects instead of having the `full_text` merged. It's just that in the default case it doesn't become apparent:
```
[{"full_text": "CPU: 4.61%", "color": "#00FF00", "instance": " 0", "name": "sysdata", "separator": false, "separator_block_width": 0},{"full_text": ", ", "instance": " 1", "name": "sysdata", "separator": false, "separator_block_width": 0},{"full_text": "Mem: 2.90/7.64 GB (37.98%)", "color": "#00FF00", "instance": " 2", "name": "sysdata"}]
```

**Comment by lasers** [comment] 2018-08-22 22:54
Closed via https://github.com/ultrabug/py3status/pull/1436.

**Closed by lasers** 2018-08-22 22:54 UTC
Labels: bug
