### ISSUE TITLE
time and tztime not updating on suspend/resume cycle

### ISSUE THREAD

**Issue by aplund** [ultrabug/py3status#2059] opened 2021-07-27 12:48 UTC
I use the tztime module (which uses the i3status command) and when I wake the machine from suspend the displayed time is wrong for a minute.  I don't display seconds ("%H:%M" format).  i3status seems to give good output when I run 'i3status -c /tmp/py3status_deadbeef'.  There must be some problem in translation in py3status under this time jump condition.

**Version**
py3status version 3.38 (python 3.9.6) on i3

(this lies, I'm on sway).

**To Reproduce**

1. Add module 'time'
2. format = '%H:%M"
3. Run py3status on sway (well, that's all I've tested it on).
4. Suspend machine
5. Resume after some long time
6. See old time displayed for a minute

**Expected behaviour**
The time should be refreshed upon resume

**Comment by ultrabug** [comment] 2021-07-28 14:16
Hi @aplund 

I think this is because your format does not use `%S` and as such py3status does not trigger an immediate refresh of i3status output, could you tell me if it works if you add seconds to the format output?

Thanks

**Comment by ultrabug** [comment] 2021-07-29 06:30
Hi again, FYI I tried your format and I sent a SIGTSTP (pause) then a SIGCONT (continue) as this is what happens when going into suspend mode... but I cannot reproduce your problem I'm afraid (i3wm here)

You should get those signals on suspend/resume and it should be confirmed in your logs if you run py3status with the `-d` flag, can you see that?

**Comment by aplund** [comment] 2021-08-05 02:38
I added a string fmt with the "%S".  Here's a screenshot after a suspend resume cycle.

Seems the tztime bits without "%S" don't update immediately.

![20210805_12h33m13s_grim](https://user-images.githubusercontent.com/1369436/128281909-61a9108d-7fbd-4516-ae4c-557c8f6da07b.png)

Note there is a 1 hour 41 minute discrepancy between the formats without "%S" compared the the last one with a "%S".

The config for the tztime elements is:

```
tztime brisbane {
        format = "%H:%M %Z"
        timezone = "Australia/Brisbane"
}

tztime berlin {
        format = "%H:%M %Z"
        timezone = "Europe/Berlin"
}

tztime local {
        format = "%Y-%m-%d %H:%M:%S %Z"
```

**Comment by aplund** [comment] 2021-08-16 02:50
I did an strace on what the py3status thread that reads from i3status sees.  I've also taken a screenshot shortly after resume.

The reading from the child process seems to be working fine.

![20210816_12h43m20s_grim](https://user-images.githubusercontent.com/1369436/129504788-495f9f1f-2c18-49ff-baa3-ea9b0de74b3e.png)

```12:23:55 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:23:55 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:23:55 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:23:55 AEST\"}]\n", 4096) = 283
12:24:00 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:24:00 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:24:00 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:24:00 AEST\"}]\n", 4096) = 283
12:24:05 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:24:05 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:24:05 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:24:05 AEST\"}]\n", 4096) = 283
12:24:10 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:24:10 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:24:10 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:24:10 AEST\"}]\n", 4096) = 283
12:24:15 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:24:15 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:24:15 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:24:15 AEST\"}]\n", 4096) = 283
12:42:49 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:42:49 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:42:49 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:42:49 AEST\"}]\n", 4096) = 283
12:42:50 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:42:50 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:42:50 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:42:50 AEST\"}]\n", 4096) = 283
12:42:55 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:42:55 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:42:55 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:42:55 AEST\"}]\n", 4096) = 283
12:43:00 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:00 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:43:00 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:00 AEST\"}]\n", 4096) = 283
12:43:05 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:05 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:43:05 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:05 AEST\"}]\n", 4096) = 283
12:43:10 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:10 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:43:10 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:10 AEST\"}]\n", 4096) = 283
12:43:15 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:15 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:43:15 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:15 AEST\"}]\n", 4096) = 283
12:43:20 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:20 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:43:20 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:20 AEST\"}]\n", 4096) = 283
12:43:25 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:25 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:43:25 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:25 AEST\"}]\n", 4096) = 283
12:43:30 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:30 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:43:30 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:30 AEST\"}]\n", 4096) = 283
12:43:35 read(7, ",[{\"name\":\"tztime\",\"instance\":\"brisbane\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:35 AEST\"},{\"name\":\"tztime\",\"instance\":\"berlin\",\"markup\":\"none\",\"full_text\":\"2021-08-16 04:43:35 CEST\"},{\"name\":\"tztime\",\"instance\":\"local\",\"markup\":\"none\",\"full_text\":\"2021-08-16 12:43:35 AEST\"}]\n", 4096) = 283
```

**Comment by aplund** [comment] 2021-08-28 00:02
I'm going to try looking into what's occuring in my particular setup.  I've tried tracing some output with a somewhat minimal configuration.  Note the discontinuity in the seconds based time.

```
$ py3status --version
py3status version 3.38 (python 3.9.6) on i3
$ i3status --version
i3status 2.13 © 2008 Michael Stapelberg and contributors
```

```
general {
        colors = true
        interval = 5
}

order += "tztime brisbane"
order += "tztime berlin"
order += "tztime local"
 

tztime brisbane {
	format = "%H:%M %Z"
	timezone = "Australia/Brisbane"
}

tztime berlin {
	format = "%H:%M %Z"
	timezone = "Europe/Berlin"
}

tztime local {
	format = "%Y-%m-%d %H:%M:%S %Z"
}
```

```
{"version": 1, "click_events": true, "stop_signal": 20}
[[]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:42:15 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:42:16 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:42:17 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:42:18 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:42:19 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:42:20 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:42:21 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:42:22 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:16 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:17 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:18 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:19 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:20 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:21 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:22 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:23 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:24 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:25 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:26 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:27 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:28 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:29 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:30 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:31 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:32 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:33 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:34 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:35 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:36 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:37 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:38 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:39 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:40 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:41 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:42 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:43 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:44 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:45 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:46 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:47 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:48 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:42 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:42 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:49 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:49 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:50 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:51 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:52 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:53 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:54 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:55 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:56 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:57 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:58 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:45 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:45 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:45:59 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:00 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:01 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:02 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:03 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:04 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:05 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:06 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:07 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:08 AEST", "name": "tztime", "instance": "local"}]
,[{"full_text": "09:46 AEST", "name": "tztime", "instance": "brisbane"},{"full_text": "01:46 CEST", "name": "tztime", "instance": "berlin"},{"full_text": "2021-08-28 09:46:09 AEST", "name": "tztime", "instance": "local"}]

```

**Comment by ultrabug** [comment] 2021-09-21 20:08
@aplund hi; I just changed my computer and I experienced a similar problem as yours where when resuming my computer after a sleep I get a SIGCONT and SIGSTP at the same time:

```
sept. 21 20:47:50 archerfish py3status[5837]: received SIGCONT
sept. 21 20:47:50 archerfish py3status[5837]: received SIGTSTP
```

which, since the SIGSTP was received last, blocks my whole py3status from updating

do you see the same stuff happening?

to unblock, I use:

```
killall -SIGCONT py3status
```

and everything resumes/refresh

**Comment by aplund** [comment] 2021-09-22 01:11
> @aplund hi; I just changed my computer and I experienced a similar problem as yours where when resuming my computer after a sleep I get a SIGCONT and SIGSTP at the same time:
> 
> ```
> sept. 21 20:47:50 archerfish py3status[5837]: received SIGCONT
> sept. 21 20:47:50 archerfish py3status[5837]: received SIGTSTP
> ```

I don't see any signals logged at all.

Logfile (suspend at 11:05:01): [py3status.log](https://github.com/ultrabug/py3status/files/7207054/py3status.log)

**Comment by aplund** [comment] 2021-10-31 23:09
I've been running version 3.39 for a while now and I don't see this issue anymore.

**Comment by ultrabug** [comment] 2021-11-05 19:29
Thanks mate, closing then

**Closed by ultrabug** 2021-11-05 19:29 UTC
