### ISSUE TITLE
Recalculate group max width after some modules start working again

### ISSUE THREAD

**Issue by ultrabug** [ultrabug/py3status#859] opened 2017-03-29 07:25 UTC
If a group has at least one of its modules reporting an error on start and then gets out of error, the space on the bar allocated to the group will not shrink back to the nominal length as it should

**Comment by tobes** [comment] 2017-03-31 11:38
Maybe I don't quite understand what the issue is here.  I've tried my best to reproduce but can't seem to.

Could you let me know how I can cause the problem.

**Comment by lasers** [comment] 2017-04-03 16:15
I think I see this ultrabug... and more ultrabugs. We use `fixed_width = True` here.

1) An exception from `group` after I dismiss `bluetooth` exception.
```
2017-04-03 09:37:57 WARNING Instance `group uptime`, user method `group` failed (UnboundLocalError) group.py line 165.
2017-04-03 09:37:57 INFO Traceback
UnboundLocalError: local variable 'current_width' referenced before assignment
  File "/home/chris/src/py3status/py3status/module.py", line 709, in run
    response = method()
  File "/home/chris/src/py3status/py3status/modules/group.py", line 209, in group
    current_output = self._get_output()
  File "/home/chris/src/py3status/py3status/modules/group.py", line 165, in _get_output
    padding = ' ' * (width - current_width)
```
2) Formatter using example `format = [up {output}]`. We want `align = center ` to work with `format` instead of `{output}`. This is because we expose placeholders everywhere. 👍
```
status_1 | up               13:20               | status_3 | status_4 | status_5
```

 3) @ultrabug's ultrabug. The difference between...
`Error`, `Expand Error`, `(Scrolling)`, There.
`Error`, `Expand Error`, `(Scrolling)`. `Collapse Error`, `(Scrolling again)`, There.

**Comment by lasers** [comment] 2017-09-05 22:23
@ultrabug Can you share the `group` config and a list of modules in that `group`? That might get us somewhere. Is this reproducible if you used `bluetooth` (code below) to throw an exception? Can we have a screenshot of `graphite` in same working state? Could it be a `graphite` issue?
```
diff --git a/py3status/modules/bluetooth.py b/py3status/modules/bluetooth.py
index e4c22884..1402e3c0 100644
--- a/py3status/modules/bluetooth.py
+++ b/py3status/modules/bluetooth.py
@@ -124,10 +124,7 @@ class Py3status:
             self.py3.log(msg)
 
     def bluetooth(self):
-        try:
-            devices = get_connected_devices()
-        except dbus.DBusException:
-            self.py3.error(STRING_NOT_STARTED)
+        devices = get_connected_devices()
 
         if devices:
             data = []
```

**Comment by lasers** [comment] 2017-10-25 06:53
Should we close this?

**Comment by tobes** [comment] 2017-10-25 09:41
@lasers thanks for your diligence

**Closed by tobes** 2017-10-25 09:41 UTC
Labels: bug
