### ISSUE TITLE
Change Py3.error() default timeout to CACHE_FOREVER

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#1114] opened 2017-10-18 13:03 UTC

**Comment by lasers** [comment] 2017-12-12 12:52
Secondary objective: Implement a global / module config to deal with exceptions.
1) `allow_exception = True` -- Expose the message.
2) `allow_exception = False` -- Hidden. Do not show anything.
3) `allow_exception = None` -- Closed. Current behavior.

**Comment by lasers** [comment] 2018-11-03 15:54
Do you want this enhancement/core PR? https://github.com/ultrabug/py3status/tree/error-timeout

**Comment by tobes** [comment] 2018-11-03 16:58
That link it to a branch So is a pain to try to look at.

**Comment by lasers** [comment] 2018-11-03 17:08
Updated to `Compare diffs`. I hope it's better to look at now.

**Comment by ultrabug** [comment] 2018-11-04 23:46
I'm not sure that the consequence of this move will have the same expected behavior on all the modules that use the py3.error

```
py3status/modules/wwan.py:            self.py3.error(STRING_MODEM_ERROR)
py3status/modules/air_quality.py:                self.py3.error(aqi_data.get('data'))
py3status/modules/bluetooth.py:            self.py3.error(STRING_NOT_STARTED)
py3status/modules/insync.py:            self.py3.error(STRING_ERROR)
py3status/modules/yubikey.py:            self.py3.error(str(self.error), self.py3.CACHE_FOREVER)
py3status/modules/imap.py:        self.mail_error = None  # cannot throw self.py3.error from thread
py3status/modules/imap.py:            self.py3.error(self.mail_error)
py3status/modules/imap.py:            self.py3.error("Server does not support IDLE")
py3status/modules/coin_market.py:                self.py3.error('bad markets')
py3status/modules/external_script.py:            self.py3.error(output)
```

**Comment by lasers** [comment] 2018-11-05 03:46
```python
air_quality.py-            elif aqi_data.get('status') == 'error':
air_quality.py:                self.py3.error(aqi_data.get('data'))
air_quality.py-
# note - A error message from the site due to invalid key or such. Should be okay.
```
```python
bluetooth.py-        except dbus.DBusException:
bluetooth.py:            self.py3.error(STRING_NOT_STARTED)
bluetooth.py-
# note - Bluetooth systemd service isn't running. Need to try this without try/except
# to see if the exception message is better. Should be okay.
```
```python
coin_market.py-            if not is_equal:
coin_market.py:                self.py3.error('bad markets')
coin_market.py-            else:
# note - This verifies the markets once at startup. When I made this, I expected the
#  module to stop there instead of keeping running in the background. Should be okay.
```
```python
external_script.py-            output = e.output or e.error
external_script.py:            self.py3.error(output)
external_script.py-
# note - Possible changed behavior.
```
```python
imap.py-            self.py3.log(self.mail_error, level=self.py3.LOG_ERROR)
imap.py:            self.py3.error(self.mail_error)
imap.py-            self.mail_error = None
imap.py-        if self.use_idle and not supports_idle:
imap.py:            self.py3.error("Server does not support IDLE")
imap.py-
# note - Possible changed behavior.
```
```python
insync.py-        if status == "Insync doesn't seem to be running. Start it first.":
insync.py:            self.py3.error(STRING_ERROR)
insync.py-        elif status == "OFFLINE":
# note - Insync systemd service isn't running. Try this without try/except
# to see if the exception message is better. Should be okay.
```
```python
wwan.py-        if wwan_data[key] == -1:
wwan.py:            self.py3.error(STRING_MODEM_ERROR)
wwan.py-        elif wwan_data[key] < 8:
# note - We were never able to trigger -1 state ourselves. Should be okay.
```
```python
yubikey.py-        if self.error:
yubikey.py:            self.py3.error(str(self.error), self.py3.CACHE_FOREVER)
yubikey.py-
# note - We didn't try resuming after an error because of restarted service since
# we didn't undo self.error message so I think it would be an unchanged behavior
# thus Should be okay.
```

**Comment by lasers** [comment] 2018-11-09 00:19
>I'm not sure that the consequence of this move will have the same expected behavior on all the modules that use the py3.error

I updated the branch with keeping `external_script` and `imap` moving if we want to make this solution part of `3.14`. Other modules looks absolutely okay to stop.

The only thing I'm not sure if we should stop is `external_script` due to offline errors, errors to be expected, or users abusing error output with different `color_error` (we had one). Scripts can be related to logging so maybe it could be better to leave it running or just stopping there (due to error).

`imap` using IDLE sometimes trigger connection errors so we need to leave this one running.

Nothing we can do for custom modules actually using `self.py3.error()`.

**Comment by tobes** [comment] 2018-11-09 10:17
For me I'd actually prefer us not to touch the `cache_timeout` at all but actually have the modules "sleep" because changing  `cache_timeout` is a dirty hack.

**Comment by lasers** [comment] 2019-05-01 15:42
Alternative PR: https://github.com/ultrabug/py3status/compare/py3-error

We don't change anything. Just `set unrecoverable errors with py3.CACHE_FOREVER` to those that needs this. IIRC it was `mpd_status` or `imap` that kept looping with `self.py3.error()` so maybe certain exceptions should be handled separately/permanently in those modules.

`external_script` and `imap` can keep working with occasional errors,  so leave them alone.

Then we could close this and @tobes could make a PR for sleeping modules later? Thoughts?

**Comment by lasers** [comment] 2019-12-10 21:19
If we make this forever, we should run `kill()` too for thread(s) in several modules.

**Closed** 2022-02-28 20:45 UTC
