### ISSUE TITLE
Add transparency/opacity

### ISSUE THREAD

**Issue by claiire** [ultrabug/py3status#1078] opened 2017-09-15 21:25 UTC
It'd be cool if there were an option to set the status bar's transparency (so the background would show through it)

**Comment by tobes** [comment] 2017-09-17 09:03
Hi,

It looks like there may be some level of support for transparency in i3bar now by setting the alpha channel in your i3 config
```
bar {
    colors {
        background #00000099
        statusline #FFFFFF99
    }
    status_command ....
}
```
I'm not sure if it works correctly as I do not use wallpapers.  If this is working I'd be happy to extend py3status' color support to include an alpha channel.

**Comment by lasers** [comment] 2017-09-22 22:38
Confirmed. Use `i3-gaps` fork and make sure to run `compton`.
```
bar {
    colors {
        background #00000099
        statusline #FFFFFF99
    }
    i3bar_command i3bar -t
    status_command py3status....
}
```
`Transparency / RGBA Colors`: https://github.com/Airblader/i3 

>I'd be happy to extend py3status' color support to include an alpha channel.

Happy to extend the `background`, `border`, and `cherrypicked borders` too?

```
background [color] sets the background color
border [color] sets the border color
border_{top, bottom, left, right} [int] sets the border width (default 1)
```

**Comment by lasers** [comment] 2019-01-04 11:54
As mentioned more than an year ago, I confirmed this. Everything works okay with 8 digit hex colors. As usual, you need to specify `i3bar -t` and run `compton`. New option `background` and `border` worked okay too. I hadn't found anything stopping me from using this. I'm closing this unless otherwise stated.

**Closed by lasers** 2019-01-04 11:54 UTC
Labels: feature request :pray:

**Comment by Strazil001** [comment] 2020-03-20 00:28
Fyi the Alpha channel comes before the color code, not after

Ex: FF000000 and not 000000FF like in the previous examples
