### ISSUE TITLE
Mpris module unexpected behaveour

### ISSUE THREAD

**Issue by valdur55** [ultrabug/py3status#963] opened 2017-07-20 10:02 UTC
Used vlc 2.2.2-5ubuntu0.16.04.3 and py3status 3.5.
Clicked on playlist view at Internet Radio section, on IceCast Radio Directory
After some loading mpris modle started toggling between current status and stop. IRL music played correctly.

To summarize this descriptiod i made video about problem: https://www.youtube.com/watch?v=AL2eiAvqNM0

Happy debugging!

**Comment by tobes** [comment] 2017-07-20 10:18
Thanks for the report is this just with icecasts?  I tried the following stream and all is fine`https://www.internet-radio.com/servers/tools/playlistgenerator/?u=http://groove.wavestreamer.com:7115/listen.pls?sid=1&t=.pls`  Do you have a url that causes the problem.

disappointed by lack of sound in your video

**Comment by valdur55** [comment] 2017-07-20 10:40
It doesn't matter which song I am playing. For example I am playing music from my computer disk and all works correctly.
It only happens when i click on IceCast Radio Directory and when loading animation finished.
After 20 all is OK again.

**Comment by lasers** [comment] 2017-09-28 13:19
Bug confirmed.
1) Open VLC with a file... as shown in the video. Otherwise, the bug does not occur.
2) Playlist --> Icecast Radio Playlist... under Internet
&nbsp;
![mpris-fires-teh-lazers](https://user-images.githubusercontent.com/852504/30967610-76ec13a2-a422-11e7-8ca8-a5b5cdf968a6.gif)

I found another bug that acts similar.
1) Open VLC without a file.
2) In Playlist --> Icecast Radio Playlist... under Internet.
3) Wait for it to load the list first before closing VLC. Otherwise, the bug does not occur.
&nbsp;
![mpris-misfiring-teh-lazers](https://user-images.githubusercontent.com/852504/30967953-53ab8002-a423-11e7-8068-8d74689ff87e.gif)

>tobes: Thanks for the report is this just with icecasts? I tried the following stream and all is fine...
disappointed by lack of sound in your video. Do you have a url that causes the problem?

It happens when the list from Icecast Radio Directory gets loaded in the playlist. No need for url.

>valdur55: Happy debugging!

You too! Happy debugging!

**Comment by lasers** [comment] 2019-01-14 19:15
@valdur55 Can you try this again? I'm not able to reproduce both bugs now.

**Comment by lasers** [comment] 2019-01-16 14:04
I'm closing this issue for the following reasons:

1) I can't reproduce both bugs anymore. I could in the past. It was not hard at all to reproduce.

2) This issue is 1 year 6 months old.

3) Compare versions. There are lot of drastic changes. This issue is stale too.

    * Used `vlc 2.2.2` + `py3status 3.5`
    * Current `vlc 3.0.6` + `py3status 3.15`

4) As far as we know, this bug only happened on vlc and hadn't happened on any other player. It may  be a vlc bug relating to opening / initializing Internet Jukebox that got fixed many moons ago.

5) My log showed that I triggered "Something went wrong" for no more than a second or two, then it becomes "no player running". It is not crazy anymore like the second screenshot.

6) You can reopen this issue if you're still experiencing this today.

Thanks for the report. Keep them coming.

**Closed by lasers** 2019-01-16 14:04 UTC
Labels: bug :disappointed:
