### ISSUE TITLE
battery_level's blocks variable doesn't handle unicode properly

### ISSUE THREAD

**Issue by rail** [ultrabug/py3status#164] opened 2016-01-16 04:03 UTC
If I use something like 
```
battery_level 0 {
    blocks = " " 
}
```
it crashes `py3status` and the nagbar shows something like
```
py3status: runtime error ('utf8' codec can't decode byte 0x89 in position 1: invalid start byte). Please try to fix and reload i3wm (Mod+Shift+R)
```

This doesn't happen when it's charging, so I guess something is wrong with https://github.com/ultrabug/py3status/blob/master/py3status/modules/battery_level.py#L287 (`self.icon = self.blocks[...`)

**Comment by ultrabug** [comment] 2016-01-16 13:53
strange @rail, I can't reproduce your bug with py2 or py3... are you running the latest battery_level module from master ?

**Comment by rail** [comment] 2016-01-16 14:16
Hmm, now that you asked, I cannot reproduce it properly either... :/
Now I don't get any nagbar errors, but have space character (0x40) instead of expected unicode one in the bar...
Just checked, I'm using 7a595c8abac314f4087aef3109ff4824efc5fc71 (current master).

**Comment by pydsigner** [comment] 2016-01-20 03:33
I'd check with various fonts to see if it's just a missing glyph in the font.

**Comment by ultrabug** [comment] 2016-02-02 16:15
@rail I'm not sure what's expected of me here plz ? :(

**Comment by rail** [comment] 2016-02-02 19:04
I managed to reproduce this. Running `py3status --debug`  and some extra `traceback.print_exc()` I get 

```
Traceback (most recent call last):
  File "/home/rail/git/py3status/py3status/__init__.py", line 1625, in main
    py3.run()
  File "/home/rail/git/py3status/py3status/__init__.py", line 1547, in run
    print_line('{}{}'.format(prefix, dumps(json_list)))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xef in position 1: invalid continuation byte
```
the value of  `json_list` is 
```json
[{'name': 'weather_yahoo', 'full_text': ''}, {'name': 'volume_status', 'full_text': ' \xef\x80\xa8 100% ', 'color': '#00FF00', 'cached_until': 1454438832.237164, 'instance': 'master', 'transformed': True}, {u'color': u'#00FF00', u'instance': u'wlp4s0', u'markup': u'none', u'name': u'wireless', u'full_text': u' \uf1eb 063% '}, {'instance': '0', 'name': 'battery_level', 'full_text': ' \xef 77% ', 'cached_until': 1454438827.232332}, {u'instance': u'NZ', u'markup': u'none', u'name': u'tztime', u'full_text': ' NZ: 07:47 '}, {u'instance': u'local', u'markup': u'none', u'name': u'tztime', u'full_text': ' Tue 02, 13:47 '}]
```

**Comment by rail** [comment] 2016-02-02 19:11
BTW, in my case `len(self.blocks)` is 16

**Comment by rail** [comment] 2016-02-02 19:56
OK. To make it work I had to modify the code that handles the icon to look like this: https://gist.github.com/rail/3a17a0e76323cd9a4dfa

The idea is that everything coming from the config is either `str`, `int` or `bool`. We need to make sure to convert it to `unicode` first (`.decode("utf8")`) to make indexes work properly. Then you need to convert it back to make sure it works with `self.format.format()` which is `str` as well.

I'm not sure if like this solution though....

**Comment by ultrabug** [comment] 2016-02-03 13:40
I guess that with your last comment you'd expect the py3status core to do this for you ?

**Comment by rail** [comment] 2016-02-03 14:36
I don't actually know... It may not work for all cases. The fact that I use UTF-8 in my config doesn't mean that everybody uses it.
Maybe this module should stop using indexes to calculate what icon to show? Maybe have a limited set of configurable icons for each state? Or use a hack to implement lists in the config (icon_1, icon_2, ...)?

**Comment by maximbaz** [comment] 2016-02-17 22:51
@rail could you make sure that your `.i3status.conf` config file is saved with utf8 encoding?

For the sake of experiment I saved my `.i3status.conf` file in `latin1` encoding (if you use vim, the command is `:set fileencoding=latin1`), after that reload i3 and I get the same issue as you ('utf-8' codec can't decode byte ...).

When I save it back in utf-8 (if you use vim, the command is `:set fileencoding=utf8`), everything works as expected, and in fact I also use unicode characters to represent battery status.

> Obviously you would lose special characters when performing such double conversion, so save a backup of your current config file first :)

**Comment by rail** [comment] 2016-02-17 23:06
Hmm, I can't even convert it to latin1 in vim. :) It complains about some conversion errors. Also
```
$ file ~/.dotfiles/.config/i3status/config
/home/rail/.dotfiles/.config/i3status/config: UTF-8 Unicode text
```
`:set fileencoding=utf8` doesn't change the file at all.

**Comment by maximbaz** [comment] 2016-02-17 23:16
Thanks, it was worth checking to eliminate the simplest ideas :) 
Out of curiosity, which python do you use? `$ py3status -v`
I think in python3 the strings are by definition unicode, so I would be "less surprised" if you say that you use python2 :)

In my case it is:
```
$ py3status -v
py3status version 2.8 (python 3.5.1)
```

**Comment by rail** [comment] 2016-02-17 23:52
Yup, exactly, switching to 3.5 fixed ALL the things. :) Apparently I my shell was automatically switching to 2.8 based virtualenv when I cd to the py3status directory. 
```
$ py3status -v
py3status version 2.8 (python 3.5.1+)
```

Feel free to close the bug, unless we need to support python2.

**Comment by rail** [comment] 2016-02-17 23:52
Thank you for spending your time helping me. :)

**Comment by pydsigner** [comment] 2016-02-17 23:53
Python 2 support is a thing.

**Comment by maximbaz** [comment] 2016-02-17 23:59
@rail you are very welcome.

I wonder if this should be a more dedicated and careful effort to "Uniformize and standardize" (:wink:) the way unicode is supported across **all** modules for both python 2 and 3. I'm sure there must be some guidelines on how to best do this, perhaps some of the existing modules have them already implemented.

**Comment by rail** [comment] 2016-02-18 00:04
Maybe [six](http://pythonhosted.org/six/)? I haven't used it for strings, but maybe they have something implemented already...

**Comment by pydsigner** [comment] 2016-02-18 00:19
It'd be good to use Unicode internally. If necessary, we can allow
specifying the config file encoding in the py3status command line args, but
otherwise running `.decode('utf-8')` on the config file contents would work.

**Comment by ultrabug** [comment] 2016-02-18 11:27
I just tried a simple force decode of the i3status values in the issue164 branch. @rail, would this solve your issue by any chance ?

**Comment by pydsigner** [comment] 2016-02-18 20:53
@ultrabug I think it might be better to do this right when the file is read to the whole file.

**Comment by tobes** [comment] 2016-07-31 22:51
PR #282 fixed this issue so we can probably close this now.

**Comment by ultrabug** [comment] 2016-08-04 07:49
Cool yeah, reopen if you feel otherwise thank you guys !

**Closed by ultrabug** 2016-08-04 07:49 UTC
Labels: bug
